// <auto-generated />
using System;
using CentroEntrenamientoFD.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentroEntrenamientoFD.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303154249_AddClientRoutineAggregate")]
    partial class AddClientRoutineAggregate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.ClientRoutine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ClientRoutines", (string)null);
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RoutineDayId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoutineDayId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.Micro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ExerciseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Micro");
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.MobilityExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientRoutineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientRoutineId");

                    b.ToTable("MobilityExercise");
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.RoutineDay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientRoutineId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DayNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientRoutineId");

                    b.ToTable("RoutineDay");
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.ClientRoutine", b =>
                {
                    b.HasOne("CentroEntrenamientoFD.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("CentroEntrenamientoFD.Domain.Entities.RoutineDay", null)
                        .WithMany("Exercises")
                        .HasForeignKey("RoutineDayId");
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.Micro", b =>
                {
                    b.HasOne("CentroEntrenamientoFD.Domain.Entities.Exercise", null)
                        .WithMany("Micros")
                        .HasForeignKey("ExerciseId");
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.MobilityExercise", b =>
                {
                    b.HasOne("CentroEntrenamientoFD.Domain.Entities.ClientRoutine", null)
                        .WithMany("Mobility")
                        .HasForeignKey("ClientRoutineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.RoutineDay", b =>
                {
                    b.HasOne("CentroEntrenamientoFD.Domain.Entities.ClientRoutine", null)
                        .WithMany("Days")
                        .HasForeignKey("ClientRoutineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.ClientRoutine", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Mobility");
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.Exercise", b =>
                {
                    b.Navigation("Micros");
                });

            modelBuilder.Entity("CentroEntrenamientoFD.Domain.Entities.RoutineDay", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
